version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: reqgather-postgres
    environment:
      POSTGRES_DB: reqgather
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reqgather-network

  redis:
    image: redis:7-alpine
    container_name: reqgather-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - reqgather-network

  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile.dev
    container_name: reqgather-api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/reqgather
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-here
      - PORT=3000
    volumes:
      - ./backend/api-gateway:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - reqgather-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: reqgather-frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_WS_URL=ws://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api-gateway
    networks:
      - reqgather-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  reqgather-network:
    driver: bridge
